#ifndef _COMPUTED_DATA_
#define _COMPUTED_DATA_

// Place holders for future calculations.
typedef struct COMPUTED_DATA {
  float T,
        T2,
        T3,
        T4,
        T5,
        TE,
        TE2,
        TE3,
        TE4,
        TE5,
        Tau,
        Tau2,
        Tau3,
        Tau4,
        Tau5,
        deltaT,
        eps0,
        eps,
        deltaPsi,
        deltaEps,
        Le,
        Be,
        Re,
        kappa,
        pi0,
        e,
        lambdaSun,
        RASun,
        DECSun,
        GHASun,
        SDSun,
        HPSun,
        EoT,
        fmtEoT,
        EoE,
        EoEout,
        Lsun_true,
        Lsun_prime,
        dES,
        dayFraction,
        GHAAmean,
        RAVenus,
        DECVenus,
        GHAVenus,
        SDVenus,
        HPVenus,
        RAMars,
        DECMars,
        GHAMars,
        SDMars,
        HPMars,
        RAJupiter,
        DECJupiter,
        GHAJupiter,
        SDJupiter,
        HPJupiter,
        RASaturn,
        DECSaturn,
        GHASaturn,
        SDSaturn,
        HPSaturn,
        RAMoon,
        DECMoon,
        GHAMoon,
        SDMoon,
        HPMoon,
        RAPol,
        DECPol,
        GHAPol,
        OoE,
        tOoE,
        LDist,
        JD0h,
        JD,
        JDE,
        lambdaMapp,
        GHAAtrue,
        moonPhaseAngle,
        illumMoon,
        illumVenus,
        illumMars,
        illumJupiter,
        illumSaturn;
  String moonPhase = "",
         SidTa,
         SidTm,
         DoW = "";
} ComputedData;

#endif
