#!/bin/bash
echo Read an ADC
#
JAVA_OPTS=
JAVA_OPTS="$JAVA_OPTS -Ddisplay.digit=true"
JAVA_OPTS="$JAVA_OPTS -Ddebug=true"
CP=./build/libs/ADC-1.0-all.jar
# sudo java -cp $CP analogdigitalconverter.ADCReader
sudo java -cp $CP $JAVA_OPTS analogdigitalconverter.mcp3008.sample.MainMCP3008Sample
