#!/bin/bash
echo Read an ADC
#
JAVA_OPTS=
JAVA_OPTS="$JAVA_OPTS -Ddisplay.digit=false"
JAVA_OPTS="$JAVA_OPTS -Ddebug=true"
CP=./build/libs/ADC-1.0-all.jar
#
echo -e "Usage is $0 --miso:9 --mosi:10 --clk:11 --cs:8 --channel:0"
#
sudo java -cp $CP $JAVA_OPTS analogdigitalconverter.mcp3008.sample.MainMCP3008Sample $*
