/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rangesensor_JNI_HC_SR04 */

#ifndef _Included_rangesensor_JNI_HC_SR04
#define _Included_rangesensor_JNI_HC_SR04
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rangesensor_JNI_HC_SR04
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_rangesensor_JNI_1HC_1SR04_init__
  (JNIEnv *, jobject);

/*
 * Class:     rangesensor_JNI_HC_SR04
 * Method:    init
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_rangesensor_JNI_1HC_1SR04_init__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     rangesensor_JNI_HC_SR04
 * Method:    readRange
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_rangesensor_JNI_1HC_1SR04_readRange
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
