#!/bin/bash
CP=
CP=$CP:./build/libs/PI4J.email-1.0-all.jar
#
OPT=
OPT="$OPT -Dmail.verbose=true"
#
# program parameters can be
# -verbose -send:google -receive:yahoo -sendto:me@home.net,you@yourplace.biz -help
#
# Note: -send:google -receive:google -sendto:akeu.coucou@gmail.com works fine. Yahoo authentication has problems :(
#
# OPT="$OPT -Dhttp.proxyHost=www-proxy.us.oracle.com"
# OPT="$OPT -Dhttp.proxyPort=80"
# OPT="$OPT -Dhttps.proxyHost=www-proxy.us.oracle.com"
# OPT="$OPT -Dhttps.proxyPort=80"
java $OPT -classpath $CP pi4j.email.SampleMain $*
# java $OPT -classpath $CP pi4j.email.SampleMain -send:google -receive:google -sendto:akeu.coucou@gmail.com
