#!/bin/bash
# Navigation REST server
#
echo -e "Starting the Navigation Rest Server"
#
HTTP_VERBOSE=false
TIDE_VERBOSE=false
ASTRO_VERBOSE=false
IMAGE_VERBOSE=true
GRIB_VERBOSE=true
#
CP=./build/libs/RESTNavServer-1.0-all.jar
JAVA_OPTS=
JAVA_OPTS="$JAVA_OPTS -DdeltaT=68.8033" # 01-June-2017
JAVA_OPTS="$JAVA_OPTS -Dhttp.verbose=$HTTP_VERBOSE"
JAVA_OPTS="$JAVA_OPTS -Dtide.verbose=$TIDE_VERBOSE"
JAVA_OPTS="$JAVA_OPTS -Dastro.verbose=$ASTRO_VERBOSE"
JAVA_OPTS="$JAVA_OPTS -Dimage.verbose=$IMAGE_VERBOSE"
JAVA_OPTS="$JAVA_OPTS -Dgrib.verbose=$GRIB_VERBOSE"
#
echo Using proxy
JAVA_OPTS="$JAVA_OPTS -Dhttp.proxyHost=www-proxy.us.oracle.com -Dhttp.proxyPort=80"
#
java -cp $CP $JAVA_OPTS navrest.NavServer
#
