#!/bin/bash
#
CP=./build/libs/SerialRxTx-1.0.jar
CP=$CP:/usr/share/java/RXTXcomm.jar
#
JAVA_OPTIONS=
# JAVA_OPTIONS="$JAVA_OPTIONS -Djava.library.path=./libs"       # for Mac
JAVA_OPTIONS="$JAVA_OPTIONS -Djava.library.path=/usr/lib/jni" # for Raspberry PI
#
SERIAL_PRMS=
# SERIAL_PRMS="$SERIAL_PRMS -Dserial.port=/dev/ttyUSB0"
SERIAL_PRMS="$SERIAL_PRMS -Dserial.port=/dev/tty.usbserial"
SERIAL_PRMS="$SERIAL_PRMS -Dbaud.rate=115200"
#
NAVITE_LIB="-Djava.library.path=/usr/lib/jni"
#
VERBOSE="-Dverbose=false"
#
java $NATIVE_LIB $SERIAL_PRMS $VERBOSE -cp $CP arduino.SerialCoommArduino
