#!/bin/bash
#
CP=./build/libs/SerialRxTx-1.0.jar
CP=$CP:/usr/share/java/RXTXcomm.jar
#
SERIAL_PRMS="-Dserial.port=/dev/ttyUSB0"
SERIAL_PRMS="$SERIAL_PRMS -Dbaud.rate=115200"
#
NAVITE_LIB="-Djava.library.path=/usr/lib/jni"
#
java $NATIVE_LIB $SERIAL_PRMS -cp $CP console.SerialConsoleCLI
