#!/bin/bash
#
CP=./build/libs/SerialRxTx-1.0.jar
CP=$CP:/usr/share/java/RXTXcomm.jar
#
java -Djava.library.path=/usr/lib/jni -Dserial.port=/dev/ttyUSB0 -Dbaud.rate=115200 -cp $CP console.SerialConsoleCLI
