#!/bin/bash
echo To install the transpiler, run:
echo sudo npm install -g es6-module-transpiler
#
echo Now transpiling
compile-modules convert -I . -o out oliv-components/widgets/*.js oliv-components/widgets/world.map/*.js --format commonjs
#
echo Done.
