#!/bin/bash
echo To install the transpiler, run:
echo sudo npm install -g es6-module-transpiler
#
echo Now transpiling
compile-modules convert -I . -o lib oliv-components/widgets/*.js --format commonjs
#
echo Done.
