package astro.celestial

class AstroContext {
  val EPS0_2000 = 23.439291111 // Reference

  // Global Variables
  var T = .0
  var T2 = .0
  var T3 = .0
  var T4 = .0
  var T5 = .0
  var TE = .0
  var TE2 = .0
  var TE3 = .0
  var TE4 = .0
  var TE5 = .0
  var Tau = .0
  var Tau2 = .0
  var Tau3 = .0
  var Tau4 = .0
  var Tau5 = .0
  var deltaT = .0
  var eps0 = .0
  var eps = .0
  var delta_psi = .0
  var delta_eps = .0
  var Le = .0
  var Be = .0
  var Re = .0
  var kappa = .0
  var pi0 = .0
  var e = .0
  var lambda_sun = .0
  var RAsun = .0
  var DECsun = .0
  var GHAsun = .0
  var SDsun = .0
  var HPsun = .0
  var EoT = .0
  var RAvenus = .0
  var DECvenus = .0
  var GHAvenus = .0
  var SDvenus = .0
  var HPvenus = .0
  var RAmars = .0
  var DECmars = .0
  var GHAmars = .0
  var SDmars = .0
  var HPmars = .0
  var RAjupiter = .0
  var DECjupiter = .0
  var GHAjupiter = .0
  var SDjupiter = .0
  var HPjupiter = .0
  var RAsaturn = .0
  var DECsaturn = .0
  var GHAsaturn = .0
  var SDsaturn = .0
  var HPsaturn = .0
  var RAmoon = .0
  var DECmoon = .0
  var GHAmoon = .0
  var SDmoon = .0
  var HPmoon = .0
  var moonEoT = .0
  var RApol = .0
  var DECpol = .0
  var GHApol = .0 //, RApolaris, DECpolaris, GHApolaris;

  var OoE = .0
  var tOoE = .0
  var LDist = .0
  var starMoonDist = .0
  var moonJupiterDist = .0
  var moonVenusDist = .0
  var moonMarsDist = .0
  var moonSaturnDist = .0
  var moonPhase = .0
  var JD0h = .0
  var JDE = .0
  var JD = .0
  var lambda = .0
  var beta = .0
  var dES = .0
  var lambdaMapp = .0
  var dayfraction = .0
  var GHAAtrue = .0
  var Lsun_mean = .0
  var Lsun_true = .0
  var k_moon = .0
  var k_venus = .0
  var k_mars = .0
  var k_jupiter = .0
  var k_saturn = .0
  var GHAstar = .0
  var SHAstar = .0
  var DECstar = .0
}
