#!/bin/bash
# 1. Interfaces
echo Interface Jars
rm -rf build > /dev/null 2>&1
mkdir build > /dev/null 2>&1
mkdir build/classes > /dev/null 2>&1
mkdir build/libs > /dev/null 2>&1
javac -d build/classes -sourcepath src/java src/java/compute/Task.java 
cd build/classes
jar -cvf ../libs/compute.jar compute/*.class
cd ../..
# 2. Server
echo Server classes
javac -d build/classes -sourcepath src/java -cp build/libs/compute.jar src/java/engine/ComputeEngine.java
# 3. Client
echo Client classes
javac -d build/classes -sourcepath src/java -cp build/libs/compute.jar src/java/client/*.java
