#!/bin/bash
CP=./build/libs/SunFlower-1.0-all.jar
#
HEADING_SERVO_ID=14
TILT_SERVO_ID=15
#
JAVA_OPTS=
JAVA_OPTS="$JAVA_OPTS -Dlatitude=37.7489 -Dlongitude=-122.5070" # SF.
JAVA_OPTS="$JAVA_OPTS -DdeltaT=68.8033" # 01-June-2017
#
JAVA_OPTS="$JAVA_OPTS -Dtest.servos=false"
#
JAVA_OPTS="$JAVA_OPTS -Dtilt.servo.sign=1"
JAVA_OPTS="$JAVA_OPTS -Dheading.servo.sign=1"
#
JAVA_OPTS="$JAVA_OPTS -Dtilt.limit=20"
JAVA_OPTS="$JAVA_OPTS -Dtilt.offset=0"
#
OPTION=basic
if [ $# -gt 0 ]
then
  OPTION=$1
fi
#
displayHelp() {
  echo "=============================================================================="
  echo "Available options are -help, basic, plus, verbose, demo, smooth."
  echo "=============================================================================="
}
#
case "$OPTION" in
  "-help" | "?" | "-h")
    displayHelp
    exit 0
    ;;
  "basic")
    JAVA_OPTS="$JAVA_OPTS -Dorient.verbose=false"
    JAVA_OPTS="$JAVA_OPTS -Dastro.verbose=false"
    JAVA_OPTS="$JAVA_OPTS -Dtilt.verbose=false"
    JAVA_OPTS="$JAVA_OPTS -Dservo.super.verbose=none"
    JAVA_OPTS="$JAVA_OPTS -Dmanual.entry=false"
    JAVA_OPTS="$JAVA_OPTS -Dansi.console=false"
    #
    JAVA_OPTS="$JAVA_OPTS -Dsmooth.moves=false"
    JAVA_OPTS="$JAVA_OPTS -Ddemo.mode=false"
    ;;
  "plus")
    JAVA_OPTS="$JAVA_OPTS -Dorient.verbose=true"
    JAVA_OPTS="$JAVA_OPTS -Dastro.verbose=true"
    JAVA_OPTS="$JAVA_OPTS -Dtilt.verbose=false"
    JAVA_OPTS="$JAVA_OPTS -Dservo.super.verbose=false"
    JAVA_OPTS="$JAVA_OPTS -Dmanual.entry=false"
    JAVA_OPTS="$JAVA_OPTS -Dansi.console=false"
    #
    JAVA_OPTS="$JAVA_OPTS -Dsmooth.moves=false"
    JAVA_OPTS="$JAVA_OPTS -Ddemo.mode=false"
    ;;
  "verbose")
    JAVA_OPTS="$JAVA_OPTS -Dorient.verbose=true"
    JAVA_OPTS="$JAVA_OPTS -Dastro.verbose=true"
    JAVA_OPTS="$JAVA_OPTS -Dtilt.verbose=false"
    JAVA_OPTS="$JAVA_OPTS -Dservo.super.verbose=false"
    JAVA_OPTS="$JAVA_OPTS -Dmanual.entry=false"
    JAVA_OPTS="$JAVA_OPTS -Dansi.console=true"
    #
    JAVA_OPTS="$JAVA_OPTS -Dsmooth.moves=false"
    JAVA_OPTS="$JAVA_OPTS -Ddemo.mode=false"
    ;;
  "demo")
    JAVA_OPTS="$JAVA_OPTS -Dorient.verbose=true"
    JAVA_OPTS="$JAVA_OPTS -Dastro.verbose=true"
    JAVA_OPTS="$JAVA_OPTS -Dtilt.verbose=false"
    JAVA_OPTS="$JAVA_OPTS -Dservo.super.verbose=false"
    JAVA_OPTS="$JAVA_OPTS -Dmanual.entry=false"
    JAVA_OPTS="$JAVA_OPTS -Dansi.console=false"
    #
    JAVA_OPTS="$JAVA_OPTS -Dsmooth.moves=false"
    JAVA_OPTS="$JAVA_OPTS -Ddemo.mode=true"
    # The 2 following ones are required if demo.mode=true
    JAVA_OPTS="$JAVA_OPTS -Dfrom.date=2017-06-28T05:53:00"
    JAVA_OPTS="$JAVA_OPTS -Dto.date=2017-06-28T20:33:00"
    ;;
  "smooth")
    JAVA_OPTS="$JAVA_OPTS -Dorient.verbose=true"
    JAVA_OPTS="$JAVA_OPTS -Dastro.verbose=true"
    JAVA_OPTS="$JAVA_OPTS -Dtilt.verbose=true"
    JAVA_OPTS="$JAVA_OPTS -Dservo.super.verbose=false"
    JAVA_OPTS="$JAVA_OPTS -Dmanual.entry=false"
    JAVA_OPTS="$JAVA_OPTS -Dansi.console=true"
    #
    JAVA_OPTS="$JAVA_OPTS -Dsmooth.moves=true"
    JAVA_OPTS="$JAVA_OPTS -Done.by.one=false"
    JAVA_OPTS="$JAVA_OPTS -Ddemo.mode=false"
    ;;
  *)
    echo "======================="
    echo "Unknown option $OPTION."
    displayHelp
    exit 1
    ;;
esac
#
sudo java -cp $CP $JAVA_OPTS orientation.SunFlower --heading:$HEADING_SERVO_ID --tilt:$TILT_SERVO_ID
