#!/bin/bash
PI4J_HOME=/opt/pi4j
CP=./classes
CP=$CP:../I2C/classes
CP=$CP:$PI4J_HOME/lib/pi4j-core.jar
JAVA_OPTS=
JAVA_OPTS="$JAVA_OPTS -Dfuzzy.verbose=true"
JAVA_OPTS="$JAVA_OPTS -Dverbose=true"
JAVA_OPTS="$JAVA_OPTS -client -agentlib:jdwp=transport=dt_socket,server=y,address=1044"
sudo java $JAVA_OPTS -cp $CP weatherstation.samples.WindDirTest
