#!/bin/bash
cd raspberry-pi4j-samples/NMEA.multiplexer
#
if [ -f ./data.nmea ]
then
  # If exits, rename it
  now=`date +%Y-%m-%d.%H:%M:%S`
  echo -e "Renaming previous data file to ${now}_data.nmea"
  sudo mv data.nmea ${now}_data.nmea
fi
nohup ./mux.sh nmea.mux.gps.log.small.properties &
echo On its way!
echo "Reach http://192.168.127.1:9999/web/index.html"
echo "  or  http://192.168.127.1:9999/web/runner.html"
