#!/bin/bash
YES=
if [ "$1" == "-y" ]
then
  YES=1
fi
cd raspberry-pi4j-samples/NMEA.multiplexer
a=
if [ "$YES" == "1" ]
then
  a=y
else 
  echo -en "Remove data.nmea ? y|n > "
  read a
fi
if [ "$a" = "y" ]
then
  echo -e "Removing previous data file"
  sudo rm data.nmea
fi
nohup ./mux.sh nmea.mux.gps.log.properties &
echo On its way!
echo "Reach http://192.168.127.1:9999/web/index.html"
echo "  or  http://192.168.127.1:9999/web/runner.html"
