#!/bin/bash
#
CP=./build/libs/RasPISamples-1.0-all.jar
#
# Requires an LSM303
#
echo Make sure you\'ve started the node server \(with websocket\) from the node directory
echo \$ node server.js
echo Once node runs, and this script runs too, you can reach http://\<machine-name\>:9876/data/pitchroll.html from a WebSocket enabled browser.
 #
JAVA_OPTIONS=
JAVA_OPTIONS="$JAVA_OPTIONS -Dlsm303.verbose=true"
# For remote debugging:
# JAVA_OPTIONS="$JAVA_OPTIONS -client -agentlib:jdwp=transport=dt_socket,server=y,address=4000"
# For remote JVM Monitoring
# JAVA_OPTIONS="$JAVA_OPTIONS -Dcom.sun.management.jmxremote.port=1234 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Djava.rmi.server.hostname=raspberrypi-boat"
echo Running...
sudo java $JAVA_OPTIONS -cp $CP pitchroll.LSM303Reader

