#!/bin/bash
JAVAC_OPTIONS="-sourcepath ./src"
JAVAC_OPTIONS="$JAVAC_OPTIONS -d ./classes"
echo $JAVAC_OPTIONS
CP=./classes
CP=$CP:../I2C/classes
CP=$CP:../GPSandSun/classes
# PI4J_HOME=/home/pi/pi4j/pi4j-distribution/target/distro-contents
CP=$CP:$PI4J_HOME/lib/pi4j-core.jar
CP=$CP:./lib/almanactools.jar
CP=$CP:./lib/geomutil.jar
CP=$CP:./lib/nauticalalmanac.jar
CP=$CP:./lib/nmeaparser.jar
CP=$CP:./lib/jansi-1.9.jar
# JAVAC_OPTIONS="-verbose $JAVAC_OPTIONS"
JAVAC_OPTIONS="$JAVAC_OPTIONS -cp $CP"
COMMAND="javac $JAVAC_OPTIONS `find ./src -name '*.java' -print`"
echo Compiling: $COMMAND
$COMMAND
echo Done

