#!/bin/bash
CP=./build/libs/GPS.sun.servo-1.0-all.jar
JAVA_OPTS=
JAVA_OPTS="$JAVA_OPTS -Dlatitude=37.7489 -Dlongitude=-122.5070 -Declination=14 -Dtolerance=3"
JAVA_OPTS="$JAVA_OPTS -Dorient.verbose=true -Dastro.verbose=true"
JAVA_OPTS="$JAVA_OPTS -Dservo.verbose=true"
#
# sudo java -cp $CP $JAVA_OPTS orientation.OrientationDetector
sudo java -cp $CP $JAVA_OPTS orientation.PanelOrienterV1 --heading:14 --tilt:15
