#!/bin/bash
CP=./build/libs/GPS.sun.servo-1.0-all.jar
JAVA_OPTS=
JAVA_OPTS="$JAVA_OPTS -Dlatitude=37.7489 -Dlongitude=-122.5070 -Declination=14" # SF, 2017.
JAVA_OPTS="$JAVA_OPTS -Dorient.verbose=false"
JAVA_OPTS="$JAVA_OPTS -Dastro.verbose=false"
JAVA_OPTS="$JAVA_OPTS -Dservo.verbose=false"
JAVA_OPTS="$JAVA_OPTS -Dservo.super.verbose=false"
JAVA_OPTS="$JAVA_OPTS -Dmanual.entry=false"
JAVA_OPTS="$JAVA_OPTS -Dansi.console=true"
#
JAVA_OPTS="$JAVA_OPTS -Dtest.servos=false"
#
JAVA_OPTS="$JAVA_OPTS -Dtilt.servo.sign=1"
JAVA_OPTS="$JAVA_OPTS -Dheading.servo.sign=1"
#
JAVA_OPTS="$JAVA_OPTS -Dtilt.limit=10"
JAVA_OPTS="$JAVA_OPTS -Dtilt.offset=0"
#
JAVA_OPTS="$JAVA_OPTS -Dsmooth.moves=true"
#
JAVA_OPTS="$JAVA_OPTS -Ddemo.mode=false"
# The 2 following ones are required if demo.mode=true
#JAVA_OPTS="$JAVA_OPTS -Dfrom.date=2017-06-28T05:53:00"
#JAVA_OPTS="$JAVA_OPTS -Dto.date=2017-06-28T20:33:00"
#
sudo java -cp $CP $JAVA_OPTS orientation.SunFlower --heading:14 --tilt:15
