/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jnisample_HelloWorld */

#ifndef _Included_jnisample_HelloWorld
#define _Included_jnisample_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jnisample_HelloWorld
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jnisample_HelloWorld_print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
