#!/bin/bash
JAVA_HOME=/usr/lib/jvm/jdk1.8.0_33
echo \>\> Compiling
javac -source 1.7 -target 1.7 -sourcepath ./src -d ./classes -classpath ./classes -g ./src/jnisample/HelloWorld.java 
echo \>\> Running javah
javah -jni -cp ./classes -d C jnisample.HelloWorld
echo \>\> Here you should implement HelloWorld.c, including jnisample_HelloWorld.h
cd C
echo \>\> Library must be named libHelloWorld.so and not only HelloWorld.so
g++ -Wall -shared -I$JAVA_HOME/include -I$JAVA_HOME/include/linux HelloWorld.c -lwiringPi -o libHelloWorld.so
cd ..
echo \>\> Now running the class invoking the native lib:
export LD_LIBRARY_PATH=./C
# ls -l $LD_LIBRARY_PATH/*.so
java -Djava.library.path=$LD_LIBRARY_PATH -cp ./classes jnisample.HelloWorld
echo \>\> Done.

